# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bitlist_development

test:
  <<: *default
  database: bitlist_test

production:
  <<: *default
  database: bitlist_production
  username: admin_max
  password: <%= ENV['1234'] %>
